### ISSUE TITLE
Add validation to param image in /generate request

### ISSUE THREAD

**Issue by AlinaYozh** [yozh-io/rundex-backend#19]
Add verification to the image parameter, if you send an empty string, then the response is 200 and there are erroneously encoded errors in the body.

**Expected result:**
When trying to send an empty string instead of an image - an error 4**

**Actual result:**
Response status 200, encoded errors in the body.

**Comment by bogdanuch41** [comment]
https://github.com/yozh-io/rundex-backend/pull/29
